name: app_post_message
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.3
  webview_flutter_wkwebview: ^3.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: '^5.1.0'
  webview_flutter_platform_interface: ^2.10.0

flutter:
  uses-material-design: true
